### ISSUE TITLE
Run Action button do nothing.

### ISSUE THREAD

**Issue by aslamiqbal** [UseHover/HoverStarter#2]
I grant all permissions. when I clicked Run Action button nothing happen.
Thanks for your project.

**Comment by davkutalek** [comment]
Hi @aslamiqbal thanks for the feedback. Have you created an action in the Hover Dashboard and put your API key and action ID into the app code?

This app is a little out of date, If you log into your Hover Dashboard you should be able to download our Hover Tester APK right from there which will allow you to run your actions right away.

**Comment by aslamiqbal** [comment]
@davkutalek 
_Have you created an action in the Hover Dashboard and put your API key and action ID into the app code?_
Yes I did. Nothing happens on emulator but show error(need internet connection error but my phone was connected to internet) in mobile.
Thanks for your reply.

**Comment by davkutalek** [comment]
Yeah, it doesn't really work in an emulator since it requires a real SIM card to run the USSD session. The no internet issue should resolve itself, sometimes it can take a minute or killing and restarting the app can help. Older versions of the SDK were also a bit buggy sometimes when detecting the network, so updating to the latest SDK (1.2.3) may help

**Comment by devzsms** [comment]
same thing happened here, 
im not using emulator,
im using real phone with dual simcard inside.

**Comment by emkaburu** [comment]
Hello Hover guys, 
I absolutely cannot get this SDK (1.6.3) to work at all. 
I have the same internet problem hence my actions cannot download. Note that I'm not using an emulator, I'm running it on a real phone from Android Studio. It can see the SIM cards present but Actions cannot download and I get the Error 2003 which is an internet problem.
And mail support from Hover is not very forth coming. @davkutalek would you mind helping us out here?

**Comment by davkutalek** [comment]
Hey @emkaburu sorry about that. The most common cause is that the API key and App package name don't match between the Hover dashboard and your app. Can you confirm that the `applicationId' in your 'build.gradle' matches what you entered for package name in the Hover dashboard?
